name: Build and Run Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t crop-recommendation .

    - name: Run container (Test)
      run: |
        docker run -d -p 5000:5000 --name crop-app crop-recommendation
        sleep 10
        curl --fail http://localhost:5000 || exit 1
